# Generated by Django 4.1.3 on 2023-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="parameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("light_intensity", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parameters",
            },
        ),
    ]
