# Generated by Django 4.1.3 on 2023-02-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="nodeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodeID", models.CharField(max_length=255)),
                ("nodePIC", models.CharField(max_length=255)),
                ("nodePICContact", models.CharField(max_length=255)),
                ("nodeLastMaintenance", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nodeDetails",
            },
        ),
        migrations.CreateModel(
            name="parameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodeID", models.CharField(max_length=255)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("light_intensity", models.FloatField()),
                ("raindrop", models.IntegerField(default=1024)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parameters",
            },
        ),
    ]
